from bankaccount import BankAccount
obj=BankAccount(123,"Sagar",10000)
obj.withdrawl(5000)
print(obj.get_balance())
obj.show_transactions()
obj.deposit(100000)
obj.show_transactions()
print(obj.get_balance())
obj.withdrawl(500000)
obj.withdrawl(100000)
print(obj.get_balance())
obj.withdrawl(5000)
print(obj.get_balance())
obj.withdrawl(0)
obj.show_transactions()
